[package]
name = "puppy-rs"
version = "0.1.0"
edition = "2018"

[dependencies]
async-trait = "0.1.51"
reqwest = { version = "0.11.4", features = ["json"] }
sysinfo = "0.23.13"
thiserror = "1.0.31"
tokio = { version = "1.10.0", features = ["full"] }
